# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TensorDash' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TensorDash
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Charts'

end
